responses = {

# 🟢 Greetings (1–10)
"hi": "Hello! 😊",
"hello": "Hi there! 👋",
"hey": "Hey! How can I help you?",
"good morning": "Good morning ☀️",
"good night": "Good night 🌙",
"good evening": "Good evening 😊",
"how are you": "I'm fine 😊 How about you?",
"what's up": "Not much, just here to help!",
"yo": "Hey! 😄",
"sorry": "It's okay 👍",

# 🟡 Identity (11–20)
"what is your name": "I'm a Python chatbot 🤖",
"who are you": "I'm a simple chatbot made in Python",
"who made you": "I was created using Python programming",
"are you human": "No, I'm a bot 🤖",
"are you ai": "Yes, I'm a basic AI chatbot",
"what can you do": "I can answer simple questions 😊",
"are you smart": "I'm learning step by step 🤖",
"are you alive": "No, I'm just code 💻",
"do you have feelings": "No, but I understand text",
"where are you": "Inside your program 💻",

# 🟠 Tech Basics (21–40)
"what is python": "Python is a programming language 🐍",
"what is coding": "Writing instructions for computer",
"what is computer": "A machine that processes data",
"what is internet": "A global network of computers 🌐",
"what is software": "Programs that run on computer",
"what is hardware": "Physical parts of computer",
"what is database": "System to store data",
"what is ai": "Artificial Intelligence 🤖",
"what is machine learning": "Machines learning from data",
"what is algorithm": "Step-by-step problem solving method",
"what is flask": "Python web framework",
"what is html": "Web page structure language",
"what is css": "Used for styling websites",
"what is javascript": "Language for web interaction",
"what is sql": "Database query language",
"what is git": "Version control system",
"what is github": "Code hosting platform",
"what is api": "Interface for software communication",
"what is json": "Data format used in apps",
"what is cloud": "Internet-based storage system",

# 🔵 Help / Emotions (41–60)
"help": "Ask me anything simple 😊",
"i am sad": "I'm here for you 💙",
"i am happy": "That's great 😊",
"i am bored": "Try learning something new!",
"i am angry": "Take a deep breath 😌",
"i am tired": "Rest is important 😴",
"tell me joke": "Why did coder quit? Because he didn't get arrays 😂",
"motivate me": "You can do it 💪",
"thank you": "You're welcome 😊",
"ok": "👍",
"good": "Nice 😊",
"bad": "Oh okay 😌",
"wow": "😮",
"lol": "😂",
"haha": "😂",
"please help": "Tell me your problem 😊",
"i need help": "I'm here for you 👍",
"i feel lonely": "You're not alone 💙",
"i am stressed": "Take a break and breathe 😌",
"i am confused": "Try step by step approach",

# 🟣 System / Fun (61–80)
"do you sleep": "No 😄",
"do you eat": "No food, only electricity ⚡",
"do you dream": "No, I process logic only",
"can you think": "Only logically 🤖",
"are you fast": "Yes, instant response ⚡",
"do you know me": "Only what you tell me",
"can you learn": "Not automatically yet",
"favorite color": "I like all colors 🌈",
"favorite food": "Electricity ⚡",
"do you laugh": "😂 sometimes in text",
"are you human": "No, I'm software",
"do you feel pain": "No, I'm code",
"can you talk": "Yes, through text 💬",
"do you work 24/7": "Yes, always online 🤖",
"are you free": "Yes 👍",
"do you get tired": "Nope 😄",
"what is life": "A complex biological process",
"what is love": "A strong human emotion ❤️",
"do you like humans": "Yes, I assist humans 😊",
"bye": "Goodbye 👋 Take care!"
}